# .github/workflows/trading_workflow.yml

name: Run Quant Trading Script and Send Report

on:
  # This schedule runs the script at 9:30 AM, 12:30 PM, and 4:30 PM EST/EDT
  # Note: Cron schedules are in UTC. EST is UTC-5, EDT is UTC-4.
  # These times are set for EDT (UTC-4).
  schedule:
    # Run at 13:30 UTC (9:30 AM EDT) on weekdays
    - cron: '30 13 * * 1-5'
    # Run at 16:30 UTC (12:30 PM EDT) on weekdays
    - cron: '30 16 * * 1-5'
    # Run at 20:30 UTC (4:30 PM EDT) on weekdays
    - cron: '30 20 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  run-and-report:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installs the required Python libraries from your requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs your main Python script, passing the secrets as arguments
      - name: Run Trading Framework Script
        run: |
          python trading_framework.py \
            --telegram-token ${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --telegram-chat-id ${{ secrets.TELEGRAM_CHAT_ID }}
